### ISSUE TITLE
Trace back error

### ISSUE THREAD

**Issue by unersov** [jtydhr88/sd-webui-txt-img-to-3d-model#21] opened 2023-07-27 20:29 UTC
Error verifying pickled file from D:\AI\stable-diffusion-webui-master\shap_e_model_cache\image_cond.pt:
Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui-master\modules\safe.py", line 136, in load_with_extra
    check_pt(filename, extra_handler)
  File "D:\AI\stable-diffusion-webui-master\modules\safe.py", line 91, in check_pt
    with z.open(data_pkl_filenames[0]) as file:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\zipfile.py", line 1532, in open
    fheader = zef_file.read(sizeFileHeader)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\zipfile.py", line 746, in read
    self._file.seek(self._pos)
OSError: [Errno 22] Invalid argument

The file may be malicious, so the program is not going to read it.
You can skip this check with --disable-safe-unpickle commandline argument.

Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui-master\venv\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\AI\stable-diffusion-webui-master\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\AI\stable-diffusion-webui-master\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\AI\stable-diffusion-webui-master\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\AI\stable-diffusion-webui-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\AI\stable-diffusion-webui-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\AI\stable-diffusion-webui-master\extensions\sd-webui-txt-img-to-3d-model\scripts\main.py", line 56, in generate
    model = load_model(model_name, device=device)
  File "D:\AI\stable-diffusion-webui-master\extensions\sd-webui-txt-img-to-3d-model\shap_e\models\download.py", line 147, in load_model
    model.load_state_dict(load_checkpoint(model_name, device=device, **kwargs))
  File "D:\AI\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1994, in load_state_dict
    raise TypeError("Expected state_dict to be dict-like, got {}.".format(type(state_dict)))
TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.

**Comment by jtydhr88** [comment] 2023-07-28 00:15
Hi @unersov , a general suggestion is to backup/rename your venv folder, then run webui-user.bat to re-download all dependencies

**Comment by jtydhr88** [comment] 2023-07-28 00:17
You can check another issue related to not working, almost all are caused by dependencies

**Comment by unersov** [comment] 2023-07-28 10:53
I just tried reinstalling dependencies, update pytorch and pip, and it still has the same error.
The txt to 3d is working fine, only img to 3d is erroring.
One thing before this error is the hash error. The image_cond.pt hash is not matching the value in the script. I tried to delete and let the script redownload the file, but the hash error remains. So I replace the new hash value in the script to bypass the check hash step. Could this be the cause?

**Comment by jtydhr88** [comment] 2023-07-29 13:46
hi @unersov , may I ask which your webui version? I tried the latest one v1.5.1 (with fresh env), and this extension works well on both txt and img mode.

**Comment by jtydhr88** [comment] 2023-07-29 13:46
![image](https://github.com/jtydhr88/sd-webui-txt-img-to-3d-model/assets/860985/6327fb26-3a49-4f6a-bd0b-ba9931cbb1cf)
![image](https://github.com/jtydhr88/sd-webui-txt-img-to-3d-model/assets/860985/42518b7b-09d8-4ebc-aed5-abbd3693dd35)

**Comment by unersov** [comment] 2023-07-30 08:21
hmmm good question I don't know, it doesn't show, let me try reinstall stable diffusion 
<img width="455" alt="image" src="https://github.com/jtydhr88/sd-webui-txt-img-to-3d-model/assets/120635341/1d508338-88a5-4aac-a10c-f17dfa916231">

**Comment by jtydhr88** [comment] 2023-08-03 13:26
if no more information coming, I would like to close this issue for now, please feel free to reopen it if the problem still exists

**Closed by jtydhr88** 2023-08-03 13:26 UTC
